RegisterCommand('fixtextures', function()
    DoScreenFadeOut(100)
    OverrideLodscaleThisFrame(0.0)
    SetIslandHopperEnabled('HeistIsland', true)
    local coords = GetEntityCoords(PlayerPedId())
    local offset_coords = vector3(coords.x + 1000, coords.y + 1000, coords.z)
    SetFocusPosAndVel(offset_coords, vector3(0, 0, 0))
    Citizen.Wait(5000)
    SetIslandHopperEnabled('HeistIsland', false)
    OverrideLodscaleThisFrame(200.0)
    ClearFocus()
    SetFocusEntity(PlayerPedId())
    DoScreenFadeIn(100)
end)
